### ISSUE TITLE
Поиск в тектограмме

### ISSUE THREAD

**Issue by Surf3r2** [LeonidOvcharenko/tectograph#1]
Заранее прошу прощения, если пишу в не предназначенном для этого месте.

Мне кажется, что замена слишком мелкого текста на "серые прямоугольники" сводит все плюсы вашего решения на нет. Я банально не могу воспользоваться поиском по странице, чтобы быстро найти нужный мне раздел или текст, если он обладает достаточно глубокой степенью вложенности. Искать вручную нужное слово в огромной простыне текста - совсем не удовольствие.

**Comment by LeonidOvcharenko** [comment]
Хром в ряде случаев рендерит шрифт не менее чем 6 пикселями, из-за чего все вложенные элементы могут разваливаться. Кроме того, визуально в мелком нечитаемом шрифте нет необходимости. Отсюда замена.
Для поиска в редакторе (но не в просмотрщике) есть специальный инструмент. Найденный элемент выделяется рамкой.

**Comment by Surf3r2** [comment]
Спасибо за ответ.
В редакторе я сразу отметил наличие этого инструмента, после чего и задал свой вопрос.

На мобильном телефоне, например, даже просмотрщиком пользоваться не очень удобно - увеличение пальцами ограничено, а кнопки +/- очень маленькие. Если говорить о редакторе - там интерфейс получается действительно слишком мелкий для пальцев - но это не тема для текущего разговора.

Я совсем не специалист по браузерам и способам рендеринга. Но мне не обязательно именно видеть слишком мелкий текст, достаточно того, что браузер сможет "видеть" (и искать) его. Или я увижу его просто увеличив страницу.

Извините за многословие, просто ваша идея меня зацепила, а воспользоваться - не могу.

**Comment by lagleki** [comment]
Хорошо бы иметь поиск именно в просмотрщике, даже по тем элементам, которые не отрендерены.

**Comment by LeonidOvcharenko** [comment]
Добавил поиск в режим просмотра.

**Comment by lagleki** [comment]
надо бы примеры gh-pages обновить под новую версию.
