### ISSUE TITLE
Скроллирование и выравнивание текста

### ISSUE THREAD

**Issue by akardapolov** [LeonidOvcharenko/tectograph#2]
Реализовать скроллинг и, одновременно, выравнивание текста блока — чтобы весь текст блока был виден, а не обрезался когда идет чуть глубокое скроллирование широких абзацов.

Выделил красным справа обрезанный текст, вот его бы не обрезать а по центру экрана, абазцом.

![new bitmap image](https://cloud.githubusercontent.com/assets/537977/11917426/1b179860-a728-11e5-9c00-11154adc9c1f.png)

**Comment by LeonidOvcharenko** [comment]
Простите, все равно не понимаю, зачем нужен скроллинг.
Тектограмма просматривается с помощью мышки как карта (скроллинг+drag'n'drop), и в режиме просмотра не перерисовывается.

Однако по скриншоту проблему кажется понял. При длинном заголовке описание становится слишком широким. Если отдалить карту, чтоб оно полностью влезало в экран, описание и вложенные элементы может быть плохо видно (из-за мелкого шрифта). Если же не отдалять, чтобы все прочесть, нужно двигать мышкой.
Так?

**Comment by akardapolov** [comment]
> > При длинном заголовке описание становится слишком широким. Если отдалить карту, чтоб оно полностью влезало в экран, описание и вложенные элементы может быть плохо видно (из-за мелкого шрифта). Если же не отдалять, чтобы все прочесть, нужно двигать мышкой.

Да, верно.

**Comment by artygrand** [comment]
Было бы не плохо, если бы работало как в браузере в смартфонах, при двойном клике зум до границ блока.

**Comment by LeonidOvcharenko** [comment]
> При длинном заголовке описание становится слишком широким.

Исправлено.

> Было бы не плохо, если бы работало как в браузере в смартфонах, при двойном клике зум до границ блока.

Сделано для вьювера.

**Comment by akardapolov** [comment]
> > > > При длинном заголовке описание становится слишком широким.
> > > > Исправлено.

А как можно протестировать? Я смотрю примеры - вроде как без изменений - текст обрезается как обычно.

**Comment by LeonidOvcharenko** [comment]
Теперь описание ограничено по ширине вне зависимости от длины заголовка:
![2015-12-24_190027](https://cloud.githubusercontent.com/assets/3919118/11996676/d00b6076-aa70-11e5-8c68-aa72be4b2822.png)
