### ISSUE TITLE
Вставка картинки из буфера

### ISSUE THREAD

**Issue by RuD91** [LeonidOvcharenko/tectograph#4]
А есть ли возможность вставлять картинки напрямую из буфера? Сохранять скриншоты на диск, а потом вставлять через ссылку не очень удобно.

**Comment by LeonidOvcharenko** [comment]
Сейчас такой возможности нет, но, думаю, нетрудно будет добавить.

**Comment by RuD91** [comment]
Если действительно нетрудно, добавьте, пожалуйста. Очень не хватает такой возможности. Спасибо!

**Comment by LeonidOvcharenko** [comment]
Добавил возможность не только вставлять картинки из буфера (Ctrl+V в том же поле «ссылка»), но и перетаскивать их с десктопа. Тестировал только под Chrome и FF.
![image](https://cloud.githubusercontent.com/assets/3919118/13550335/09bc4998-e324-11e5-8fbf-15e8d7a3f8d2.png)

**Comment by RuD91** [comment]
Спасибо огромное?  Есть возможность оказать небольшую поддержку проекту?

**Comment by LeonidOvcharenko** [comment]
На данный момент больше всего нужна обратная связь: кто, для чего и как использует программу. После этого можно решать, куда двигаться дальше. Тогда и помощь в разработке нужна будет.

**Comment by Thermik** [comment]
Леонид, добрый день! А можно ли использовать Текстограф в качестве инструмента по созданию "одностраничного" сайта. Те чтобы был режим редактирования и режим просмотра всеми остальными. Мне представляется что это перспективное направление, когда, например верстается сайт для разового события (фестиваль, праздник) то администратор быстро "накидывает" необходимую информацию. А все остальные видят его как сайт.

**Comment by ildar** [comment]
Можно попробовать преобразовать тектограмму в, например, DocBook, а тот уже
в сайт.

> ## 
> 
> Ildar Mulyukov,
> child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by LeonidOvcharenko** [comment]
Использовать тектограф как инструмент для создания сайтов сейчас нельзя. В режиме админки нужно где-то сохранять данные, чтоб в режиме просмотра оттуда их брать. Нужна серверная часть. К тому же делать общедоступный сайт на основе просмотрщика сейчас не целесообразно из-за проблем с отображением тектограмм в IE.
Если быстрые изменения не важны, то да, тектограмму экспортировать в html/xml, и на основе их делать страничку.

Исходный вопрос «Вставка картинки из буфера» решен, issue закрываю.
