### ISSUE TITLE
Не работает в редакторе режим отображения графа

### ISSUE THREAD

**Issue by ivan133** [LeonidOvcharenko/tectograph#5]
Mac Os 10.10.5
Google chrome Версия 49.0.2623.110 (64-bit)
1. захожу (3й пример) https://dl.dropboxusercontent.com/s/jkzv0zvse1r1tjd/user-iterface.json?dl=0##1
2. скачиваю json
3. захожу в хроме в приватном режиме http://leonidovcharenko.github.io/tectograph/#
4. Выбираю: Схема -> Открыть
5. Выскакивает ошибка 

`svg.js:2 Uncaught TypeError: Cannot read property 'numberOfItems' of undefined`

[Ссылка на скриншот](https://gyazo.com/35e27212f3b2b1692d01c1ec24fab188)

Так же у меня не работает и если вручную создать.
Зайти в режим упрощенного редактора и вставить туда

```

- Empty system
  - Empty system
  - - Empty system
  - - - Empty system
  - - - - Empty system
    - - - - - Empty system
    - - - - - - Empty system 
```

Далее выбрать родительский граф, создать в нем задать Структура - Граф

**Comment by LeonidOvcharenko** [comment]
Исправил обновлением svg.js.

**Comment by ivan133** [comment]
Работает!
